/**
 * World Countries — ISO Alpha-3 codes & estimated public investment 2024.
 * Sources: IMF World Economic Outlook (Oct 2024), World Bank, national statistics.
 * Public investment = Govt Gross Fixed Capital Formation. All figures are estimates.
 *
 * Fields:
 *   iso3          — ISO 3166-1 alpha-3 code (primary key in DB)
 *   name          — Country name
 *   gdpBn         — GDP 2024 (USD Billions, Est.)
 *   pubInvPctGdp  — Public Investment as % of GDP (Est.), stored as decimal e.g. 0.045
 *   pubInvBn      — Public Investment 2024 (USD Billions, Est.) = gdpBn × pubInvPctGdp
 */
export interface CountryData {
  iso3: string;
  name: string;
  gdpBn: number;
  pubInvPctGdp: number;
  pubInvBn: number;
}

export const COUNTRIES_DATA: CountryData[] = [
  { iso3: "AFG", name: "Afghanistan",                      gdpBn: 14.6,   pubInvPctGdp: 0.045, pubInvBn: 0.657   },
  { iso3: "ALB", name: "Albania",                          gdpBn: 23,     pubInvPctGdp: 0.042, pubInvBn: 0.966   },
  { iso3: "DZA", name: "Algeria",                          gdpBn: 238,    pubInvPctGdp: 0.065, pubInvBn: 15.47   },
  { iso3: "AND", name: "Andorra",                          gdpBn: 3.4,    pubInvPctGdp: 0.028, pubInvBn: 0.095   },
  { iso3: "AGO", name: "Angola",                           gdpBn: 91,     pubInvPctGdp: 0.05,  pubInvBn: 4.55    },
  { iso3: "ATG", name: "Antigua and Barbuda",              gdpBn: 2,      pubInvPctGdp: 0.045, pubInvBn: 0.09    },
  { iso3: "ARG", name: "Argentina",                        gdpBn: 641,    pubInvPctGdp: 0.028, pubInvBn: 17.948  },
  { iso3: "ARM", name: "Armenia",                          gdpBn: 22,     pubInvPctGdp: 0.04,  pubInvBn: 0.88    },
  { iso3: "AUS", name: "Australia",                        gdpBn: 1724,   pubInvPctGdp: 0.034, pubInvBn: 58.616  },
  { iso3: "AUT", name: "Austria",                          gdpBn: 521,    pubInvPctGdp: 0.03,  pubInvBn: 15.63   },
  { iso3: "AZE", name: "Azerbaijan",                       gdpBn: 72,     pubInvPctGdp: 0.06,  pubInvBn: 4.32    },
  { iso3: "BHS", name: "Bahamas",                          gdpBn: 14,     pubInvPctGdp: 0.035, pubInvBn: 0.49    },
  { iso3: "BHR", name: "Bahrain",                          gdpBn: 43,     pubInvPctGdp: 0.065, pubInvBn: 2.795   },
  { iso3: "BGD", name: "Bangladesh",                       gdpBn: 450,    pubInvPctGdp: 0.045, pubInvBn: 20.25   },
  { iso3: "BRB", name: "Barbados",                         gdpBn: 6,      pubInvPctGdp: 0.035, pubInvBn: 0.21    },
  { iso3: "BLR", name: "Belarus",                          gdpBn: 75,     pubInvPctGdp: 0.045, pubInvBn: 3.375   },
  { iso3: "BEL", name: "Belgium",                          gdpBn: 623,    pubInvPctGdp: 0.028, pubInvBn: 17.444  },
  { iso3: "BLZ", name: "Belize",                           gdpBn: 3.1,    pubInvPctGdp: 0.04,  pubInvBn: 0.124   },
  { iso3: "BEN", name: "Benin",                            gdpBn: 17,     pubInvPctGdp: 0.055, pubInvBn: 0.935   },
  { iso3: "BTN", name: "Bhutan",                           gdpBn: 3,      pubInvPctGdp: 0.07,  pubInvBn: 0.21    },
  { iso3: "BOL", name: "Bolivia",                          gdpBn: 44,     pubInvPctGdp: 0.05,  pubInvBn: 2.2     },
  { iso3: "BIH", name: "Bosnia and Herzegovina",           gdpBn: 25,     pubInvPctGdp: 0.04,  pubInvBn: 1.0     },
  { iso3: "BWA", name: "Botswana",                         gdpBn: 21,     pubInvPctGdp: 0.042, pubInvBn: 0.882   },
  { iso3: "BRA", name: "Brazil",                           gdpBn: 2173,   pubInvPctGdp: 0.025, pubInvBn: 54.325  },
  { iso3: "BRN", name: "Brunei Darussalam",                gdpBn: 16,     pubInvPctGdp: 0.055, pubInvBn: 0.88    },
  { iso3: "BGR", name: "Bulgaria",                         gdpBn: 101,    pubInvPctGdp: 0.035, pubInvBn: 3.535   },
  { iso3: "BFA", name: "Burkina Faso",                     gdpBn: 17,     pubInvPctGdp: 0.045, pubInvBn: 0.765   },
  { iso3: "BDI", name: "Burundi",                          gdpBn: 3.1,    pubInvPctGdp: 0.04,  pubInvBn: 0.124   },
  { iso3: "CPV", name: "Cabo Verde",                       gdpBn: 2.2,    pubInvPctGdp: 0.055, pubInvBn: 0.121   },
  { iso3: "KHM", name: "Cambodia",                         gdpBn: 32,     pubInvPctGdp: 0.055, pubInvBn: 1.76    },
  { iso3: "CMR", name: "Cameroon",                         gdpBn: 47,     pubInvPctGdp: 0.045, pubInvBn: 2.115   },
  { iso3: "CAN", name: "Canada",                           gdpBn: 2140,   pubInvPctGdp: 0.035, pubInvBn: 74.9    },
  { iso3: "CAF", name: "Central African Republic",         gdpBn: 2.4,    pubInvPctGdp: 0.04,  pubInvBn: 0.096   },
  { iso3: "TCD", name: "Chad",                             gdpBn: 11,     pubInvPctGdp: 0.04,  pubInvBn: 0.44    },
  { iso3: "CHL", name: "Chile",                            gdpBn: 317,    pubInvPctGdp: 0.03,  pubInvBn: 9.51    },
  { iso3: "CHN", name: "China",                            gdpBn: 18500,  pubInvPctGdp: 0.08,  pubInvBn: 1480.0  },
  { iso3: "COL", name: "Colombia",                         gdpBn: 363,    pubInvPctGdp: 0.03,  pubInvBn: 10.89   },
  { iso3: "COM", name: "Comoros",                          gdpBn: 1.3,    pubInvPctGdp: 0.045, pubInvBn: 0.058   },
  { iso3: "COG", name: "Congo, Republic",                  gdpBn: 12,     pubInvPctGdp: 0.05,  pubInvBn: 0.6     },
  { iso3: "COD", name: "Congo, Dem. Rep.",                 gdpBn: 66,     pubInvPctGdp: 0.045, pubInvBn: 2.97    },
  { iso3: "CRI", name: "Costa Rica",                       gdpBn: 80,     pubInvPctGdp: 0.035, pubInvBn: 2.8     },
  { iso3: "CIV", name: "Côte d'Ivoire",                   gdpBn: 70,     pubInvPctGdp: 0.055, pubInvBn: 3.85    },
  { iso3: "HRV", name: "Croatia",                          gdpBn: 84,     pubInvPctGdp: 0.035, pubInvBn: 2.94    },
  { iso3: "CUB", name: "Cuba",                             gdpBn: 107,    pubInvPctGdp: 0.055, pubInvBn: 5.885   },
  { iso3: "CYP", name: "Cyprus",                           gdpBn: 34,     pubInvPctGdp: 0.035, pubInvBn: 1.19    },
  { iso3: "CZE", name: "Czechia",                          gdpBn: 335,    pubInvPctGdp: 0.035, pubInvBn: 11.725  },
  { iso3: "DNK", name: "Denmark",                          gdpBn: 407,    pubInvPctGdp: 0.03,  pubInvBn: 12.21   },
  { iso3: "DJI", name: "Djibouti",                         gdpBn: 4,      pubInvPctGdp: 0.06,  pubInvBn: 0.24    },
  { iso3: "DMA", name: "Dominica",                         gdpBn: 0.6,    pubInvPctGdp: 0.05,  pubInvBn: 0.03    },
  { iso3: "DOM", name: "Dominican Republic",               gdpBn: 113,    pubInvPctGdp: 0.04,  pubInvBn: 4.52    },
  { iso3: "ECU", name: "Ecuador",                          gdpBn: 118,    pubInvPctGdp: 0.04,  pubInvBn: 4.72    },
  { iso3: "EGY", name: "Egypt",                            gdpBn: 347,    pubInvPctGdp: 0.045, pubInvBn: 15.615  },
  { iso3: "SLV", name: "El Salvador",                      gdpBn: 34,     pubInvPctGdp: 0.045, pubInvBn: 1.53    },
  { iso3: "GNQ", name: "Equatorial Guinea",                gdpBn: 12,     pubInvPctGdp: 0.055, pubInvBn: 0.66    },
  { iso3: "ERI", name: "Eritrea",                          gdpBn: 2,      pubInvPctGdp: 0.05,  pubInvBn: 0.1     },
  { iso3: "EST", name: "Estonia",                          gdpBn: 43,     pubInvPctGdp: 0.035, pubInvBn: 1.505   },
  { iso3: "SWZ", name: "Eswatini",                         gdpBn: 4.5,    pubInvPctGdp: 0.045, pubInvBn: 0.202   },
  { iso3: "ETH", name: "Ethiopia",                         gdpBn: 155,    pubInvPctGdp: 0.055, pubInvBn: 8.525   },
  { iso3: "FJI", name: "Fiji",                             gdpBn: 5,      pubInvPctGdp: 0.05,  pubInvBn: 0.25    },
  { iso3: "FIN", name: "Finland",                          gdpBn: 305,    pubInvPctGdp: 0.035, pubInvBn: 10.675  },
  { iso3: "FRA", name: "France",                           gdpBn: 3031,   pubInvPctGdp: 0.035, pubInvBn: 106.085 },
  { iso3: "GAB", name: "Gabon",                            gdpBn: 21,     pubInvPctGdp: 0.05,  pubInvBn: 1.05    },
  { iso3: "GMB", name: "Gambia",                           gdpBn: 2,      pubInvPctGdp: 0.045, pubInvBn: 0.09    },
  { iso3: "GEO", name: "Georgia",                          gdpBn: 25,     pubInvPctGdp: 0.05,  pubInvBn: 1.25    },
  { iso3: "DEU", name: "Germany",                          gdpBn: 4456,   pubInvPctGdp: 0.028, pubInvBn: 124.768 },
  { iso3: "GHA", name: "Ghana",                            gdpBn: 77,     pubInvPctGdp: 0.04,  pubInvBn: 3.08    },
  { iso3: "GRC", name: "Greece",                           gdpBn: 239,    pubInvPctGdp: 0.03,  pubInvBn: 7.17    },
  { iso3: "GRD", name: "Grenada",                          gdpBn: 1.3,    pubInvPctGdp: 0.05,  pubInvBn: 0.065   },
  { iso3: "GTM", name: "Guatemala",                        gdpBn: 102,    pubInvPctGdp: 0.035, pubInvBn: 3.57    },
  { iso3: "GIN", name: "Guinea",                           gdpBn: 15,     pubInvPctGdp: 0.045, pubInvBn: 0.675   },
  { iso3: "GNB", name: "Guinea-Bissau",                    gdpBn: 1.5,    pubInvPctGdp: 0.045, pubInvBn: 0.068   },
  { iso3: "GUY", name: "Guyana",                           gdpBn: 22,     pubInvPctGdp: 0.08,  pubInvBn: 1.76    },
  { iso3: "HTI", name: "Haiti",                            gdpBn: 20,     pubInvPctGdp: 0.035, pubInvBn: 0.7     },
  { iso3: "HND", name: "Honduras",                         gdpBn: 32,     pubInvPctGdp: 0.045, pubInvBn: 1.44    },
  { iso3: "HUN", name: "Hungary",                          gdpBn: 211,    pubInvPctGdp: 0.035, pubInvBn: 7.385   },
  { iso3: "ISL", name: "Iceland",                          gdpBn: 28,     pubInvPctGdp: 0.045, pubInvBn: 1.26    },
  { iso3: "IND", name: "India",                            gdpBn: 3937,   pubInvPctGdp: 0.048, pubInvBn: 188.976 },
  { iso3: "IDN", name: "Indonesia",                        gdpBn: 1477,   pubInvPctGdp: 0.045, pubInvBn: 66.465  },
  { iso3: "IRN", name: "Iran",                             gdpBn: 401,    pubInvPctGdp: 0.045, pubInvBn: 18.045  },
  { iso3: "IRQ", name: "Iraq",                             gdpBn: 264,    pubInvPctGdp: 0.075, pubInvBn: 19.8    },
  { iso3: "IRL", name: "Ireland",                          gdpBn: 560,    pubInvPctGdp: 0.025, pubInvBn: 14.0    },
  { iso3: "ISR", name: "Israel",                           gdpBn: 522,    pubInvPctGdp: 0.035, pubInvBn: 18.27   },
  { iso3: "ITA", name: "Italy",                            gdpBn: 2254,   pubInvPctGdp: 0.025, pubInvBn: 56.35   },
  { iso3: "JAM", name: "Jamaica",                          gdpBn: 18,     pubInvPctGdp: 0.035, pubInvBn: 0.63    },
  { iso3: "JPN", name: "Japan",                            gdpBn: 4213,   pubInvPctGdp: 0.035, pubInvBn: 147.455 },
  { iso3: "JOR", name: "Jordan",                           gdpBn: 46,     pubInvPctGdp: 0.055, pubInvBn: 2.53    },
  { iso3: "KAZ", name: "Kazakhstan",                       gdpBn: 261,    pubInvPctGdp: 0.055, pubInvBn: 14.355  },
  { iso3: "KEN", name: "Kenya",                            gdpBn: 107,    pubInvPctGdp: 0.045, pubInvBn: 4.815   },
  { iso3: "KIR", name: "Kiribati",                         gdpBn: 0.25,   pubInvPctGdp: 0.08,  pubInvBn: 0.02    },
  { iso3: "PRK", name: "Korea, North",                     gdpBn: 40,     pubInvPctGdp: 0.06,  pubInvBn: 2.4     },
  { iso3: "KOR", name: "Korea, South",                     gdpBn: 1712,   pubInvPctGdp: 0.045, pubInvBn: 77.04   },
  { iso3: "KWT", name: "Kuwait",                           gdpBn: 162,    pubInvPctGdp: 0.065, pubInvBn: 10.53   },
  { iso3: "KGZ", name: "Kyrgyzstan",                       gdpBn: 13,     pubInvPctGdp: 0.055, pubInvBn: 0.715   },
  { iso3: "LAO", name: "Laos",                             gdpBn: 16,     pubInvPctGdp: 0.065, pubInvBn: 1.04    },
  { iso3: "LVA", name: "Latvia",                           gdpBn: 47,     pubInvPctGdp: 0.04,  pubInvBn: 1.88    },
  { iso3: "LBN", name: "Lebanon",                          gdpBn: 19,     pubInvPctGdp: 0.02,  pubInvBn: 0.38    },
  { iso3: "LSO", name: "Lesotho",                          gdpBn: 2.5,    pubInvPctGdp: 0.05,  pubInvBn: 0.125   },
  { iso3: "LBR", name: "Liberia",                          gdpBn: 3,      pubInvPctGdp: 0.045, pubInvBn: 0.135   },
  { iso3: "LBY", name: "Libya",                            gdpBn: 54,     pubInvPctGdp: 0.06,  pubInvBn: 3.24    },
  { iso3: "LIE", name: "Liechtenstein",                    gdpBn: 7.3,    pubInvPctGdp: 0.025, pubInvBn: 0.182   },
  { iso3: "LTU", name: "Lithuania",                        gdpBn: 76,     pubInvPctGdp: 0.035, pubInvBn: 2.66    },
  { iso3: "LUX", name: "Luxembourg",                       gdpBn: 90,     pubInvPctGdp: 0.035, pubInvBn: 3.15    },
  { iso3: "MDG", name: "Madagascar",                       gdpBn: 14,     pubInvPctGdp: 0.045, pubInvBn: 0.63    },
  { iso3: "MWI", name: "Malawi",                           gdpBn: 13,     pubInvPctGdp: 0.045, pubInvBn: 0.585   },
  { iso3: "MYS", name: "Malaysia",                         gdpBn: 430,    pubInvPctGdp: 0.045, pubInvBn: 19.35   },
  { iso3: "MDV", name: "Maldives",                         gdpBn: 7,      pubInvPctGdp: 0.07,  pubInvBn: 0.49    },
  { iso3: "MLI", name: "Mali",                             gdpBn: 19,     pubInvPctGdp: 0.05,  pubInvBn: 0.95    },
  { iso3: "MLT", name: "Malta",                            gdpBn: 18,     pubInvPctGdp: 0.035, pubInvBn: 0.63    },
  { iso3: "MHL", name: "Marshall Islands",                 gdpBn: 0.3,    pubInvPctGdp: 0.09,  pubInvBn: 0.027   },
  { iso3: "MRT", name: "Mauritania",                       gdpBn: 9,      pubInvPctGdp: 0.055, pubInvBn: 0.495   },
  { iso3: "MUS", name: "Mauritius",                        gdpBn: 14,     pubInvPctGdp: 0.04,  pubInvBn: 0.56    },
  { iso3: "MEX", name: "Mexico",                           gdpBn: 1788,   pubInvPctGdp: 0.028, pubInvBn: 50.064  },
  { iso3: "FSM", name: "Micronesia, Fed. States",          gdpBn: 0.4,    pubInvPctGdp: 0.08,  pubInvBn: 0.032   },
  { iso3: "MDA", name: "Moldova",                          gdpBn: 15,     pubInvPctGdp: 0.04,  pubInvBn: 0.6     },
  { iso3: "MCO", name: "Monaco",                           gdpBn: 8.6,    pubInvPctGdp: 0.03,  pubInvBn: 0.258   },
  { iso3: "MNG", name: "Mongolia",                         gdpBn: 20,     pubInvPctGdp: 0.065, pubInvBn: 1.3     },
  { iso3: "MNE", name: "Montenegro",                       gdpBn: 7,      pubInvPctGdp: 0.045, pubInvBn: 0.315   },
  { iso3: "MAR", name: "Morocco",                          gdpBn: 142,    pubInvPctGdp: 0.055, pubInvBn: 7.81    },
  { iso3: "MOZ", name: "Mozambique",                       gdpBn: 18,     pubInvPctGdp: 0.05,  pubInvBn: 0.9     },
  { iso3: "MMR", name: "Myanmar",                          gdpBn: 64,     pubInvPctGdp: 0.045, pubInvBn: 2.88    },
  { iso3: "NAM", name: "Namibia",                          gdpBn: 14,     pubInvPctGdp: 0.05,  pubInvBn: 0.7     },
  { iso3: "NRU", name: "Nauru",                            gdpBn: 0.15,   pubInvPctGdp: 0.08,  pubInvBn: 0.012   },
  { iso3: "NPL", name: "Nepal",                            gdpBn: 40,     pubInvPctGdp: 0.05,  pubInvBn: 2.0     },
  { iso3: "NLD", name: "Netherlands",                      gdpBn: 1122,   pubInvPctGdp: 0.03,  pubInvBn: 33.66   },
  { iso3: "NZL", name: "New Zealand",                      gdpBn: 245,    pubInvPctGdp: 0.035, pubInvBn: 8.575   },
  { iso3: "NIC", name: "Nicaragua",                        gdpBn: 18,     pubInvPctGdp: 0.045, pubInvBn: 0.81    },
  { iso3: "NER", name: "Niger",                            gdpBn: 14,     pubInvPctGdp: 0.05,  pubInvBn: 0.7     },
  { iso3: "NGA", name: "Nigeria",                          gdpBn: 400,    pubInvPctGdp: 0.035, pubInvBn: 14.0    },
  { iso3: "MKD", name: "North Macedonia",                  gdpBn: 14,     pubInvPctGdp: 0.045, pubInvBn: 0.63    },
  { iso3: "NOR", name: "Norway",                           gdpBn: 548,    pubInvPctGdp: 0.04,  pubInvBn: 21.92   },
  { iso3: "OMN", name: "Oman",                             gdpBn: 108,    pubInvPctGdp: 0.075, pubInvBn: 8.1     },
  { iso3: "PAK", name: "Pakistan",                         gdpBn: 338,    pubInvPctGdp: 0.035, pubInvBn: 11.83   },
  { iso3: "PLW", name: "Palau",                            gdpBn: 0.3,    pubInvPctGdp: 0.08,  pubInvBn: 0.024   },
  { iso3: "PSE", name: "Palestine",                        gdpBn: 18,     pubInvPctGdp: 0.04,  pubInvBn: 0.72    },
  { iso3: "PAN", name: "Panama",                           gdpBn: 79,     pubInvPctGdp: 0.045, pubInvBn: 3.555   },
  { iso3: "PNG", name: "Papua New Guinea",                 gdpBn: 29,     pubInvPctGdp: 0.06,  pubInvBn: 1.74    },
  { iso3: "PRY", name: "Paraguay",                         gdpBn: 43,     pubInvPctGdp: 0.04,  pubInvBn: 1.72    },
  { iso3: "PER", name: "Peru",                             gdpBn: 269,    pubInvPctGdp: 0.04,  pubInvBn: 10.76   },
  { iso3: "PHL", name: "Philippines",                      gdpBn: 437,    pubInvPctGdp: 0.055, pubInvBn: 24.035  },
  { iso3: "POL", name: "Poland",                           gdpBn: 842,    pubInvPctGdp: 0.04,  pubInvBn: 33.68   },
  { iso3: "PRT", name: "Portugal",                         gdpBn: 268,    pubInvPctGdp: 0.03,  pubInvBn: 8.04    },
  { iso3: "QAT", name: "Qatar",                            gdpBn: 236,    pubInvPctGdp: 0.085, pubInvBn: 20.06   },
  { iso3: "ROU", name: "Romania",                          gdpBn: 350,    pubInvPctGdp: 0.04,  pubInvBn: 14.0    },
  { iso3: "RUS", name: "Russia",                           gdpBn: 2062,   pubInvPctGdp: 0.05,  pubInvBn: 103.1   },
  { iso3: "RWA", name: "Rwanda",                           gdpBn: 14,     pubInvPctGdp: 0.06,  pubInvBn: 0.84    },
  { iso3: "KNA", name: "Saint Kitts and Nevis",            gdpBn: 1.1,    pubInvPctGdp: 0.05,  pubInvBn: 0.055   },
  { iso3: "LCA", name: "Saint Lucia",                      gdpBn: 2.4,    pubInvPctGdp: 0.05,  pubInvBn: 0.12    },
  { iso3: "VCT", name: "Saint Vincent & the Grenadines",   gdpBn: 1,      pubInvPctGdp: 0.055, pubInvBn: 0.055   },
  { iso3: "WSM", name: "Samoa",                            gdpBn: 1,      pubInvPctGdp: 0.07,  pubInvBn: 0.07    },
  { iso3: "SMR", name: "San Marino",                       gdpBn: 1.8,    pubInvPctGdp: 0.03,  pubInvBn: 0.054   },
  { iso3: "STP", name: "São Tomé and Príncipe",            gdpBn: 0.7,    pubInvPctGdp: 0.055, pubInvBn: 0.038   },
  { iso3: "SAU", name: "Saudi Arabia",                     gdpBn: 1067,   pubInvPctGdp: 0.085, pubInvBn: 90.695  },
  { iso3: "SEN", name: "Senegal",                          gdpBn: 31,     pubInvPctGdp: 0.055, pubInvBn: 1.705   },
  { iso3: "SRB", name: "Serbia",                           gdpBn: 68,     pubInvPctGdp: 0.045, pubInvBn: 3.06    },
  { iso3: "SYC", name: "Seychelles",                       gdpBn: 2,      pubInvPctGdp: 0.06,  pubInvBn: 0.12    },
  { iso3: "SLE", name: "Sierra Leone",                     gdpBn: 4,      pubInvPctGdp: 0.045, pubInvBn: 0.18    },
  { iso3: "SGP", name: "Singapore",                        gdpBn: 497,    pubInvPctGdp: 0.04,  pubInvBn: 19.88   },
  { iso3: "SVK", name: "Slovakia",                         gdpBn: 137,    pubInvPctGdp: 0.035, pubInvBn: 4.795   },
  { iso3: "SVN", name: "Slovenia",                         gdpBn: 67,     pubInvPctGdp: 0.035, pubInvBn: 2.345   },
  { iso3: "SLB", name: "Solomon Islands",                  gdpBn: 1.6,    pubInvPctGdp: 0.07,  pubInvBn: 0.112   },
  { iso3: "SOM", name: "Somalia",                          gdpBn: 8,      pubInvPctGdp: 0.04,  pubInvBn: 0.32    },
  { iso3: "ZAF", name: "South Africa",                     gdpBn: 373,    pubInvPctGdp: 0.035, pubInvBn: 13.055  },
  { iso3: "SSD", name: "South Sudan",                      gdpBn: 3,      pubInvPctGdp: 0.04,  pubInvBn: 0.12    },
  { iso3: "ESP", name: "Spain",                            gdpBn: 1580,   pubInvPctGdp: 0.03,  pubInvBn: 47.4    },
  { iso3: "LKA", name: "Sri Lanka",                        gdpBn: 87,     pubInvPctGdp: 0.04,  pubInvBn: 3.48    },
  { iso3: "SDN", name: "Sudan",                            gdpBn: 30,     pubInvPctGdp: 0.035, pubInvBn: 1.05    },
  { iso3: "SUR", name: "Suriname",                         gdpBn: 4,      pubInvPctGdp: 0.04,  pubInvBn: 0.16    },
  { iso3: "SWE", name: "Sweden",                           gdpBn: 593,    pubInvPctGdp: 0.04,  pubInvBn: 23.72   },
  { iso3: "CHE", name: "Switzerland",                      gdpBn: 905,    pubInvPctGdp: 0.03,  pubInvBn: 27.15   },
  { iso3: "SYR", name: "Syria",                            gdpBn: 12,     pubInvPctGdp: 0.035, pubInvBn: 0.42    },
  { iso3: "TWN", name: "Taiwan",                           gdpBn: 760,    pubInvPctGdp: 0.045, pubInvBn: 34.2    },
  { iso3: "TJK", name: "Tajikistan",                       gdpBn: 10,     pubInvPctGdp: 0.06,  pubInvBn: 0.6     },
  { iso3: "TZA", name: "Tanzania",                         gdpBn: 85,     pubInvPctGdp: 0.055, pubInvBn: 4.675   },
  { iso3: "THA", name: "Thailand",                         gdpBn: 519,    pubInvPctGdp: 0.045, pubInvBn: 23.355  },
  { iso3: "TLS", name: "Timor-Leste",                      gdpBn: 3,      pubInvPctGdp: 0.075, pubInvBn: 0.225   },
  { iso3: "TGO", name: "Togo",                             gdpBn: 8,      pubInvPctGdp: 0.05,  pubInvBn: 0.4     },
  { iso3: "TON", name: "Tonga",                            gdpBn: 0.5,    pubInvPctGdp: 0.075, pubInvBn: 0.037   },
  { iso3: "TTO", name: "Trinidad and Tobago",              gdpBn: 26,     pubInvPctGdp: 0.055, pubInvBn: 1.43    },
  { iso3: "TUN", name: "Tunisia",                          gdpBn: 48,     pubInvPctGdp: 0.045, pubInvBn: 2.16    },
  { iso3: "TUR", name: "Turkey",                           gdpBn: 1344,   pubInvPctGdp: 0.045, pubInvBn: 60.48   },
  { iso3: "TKM", name: "Turkmenistan",                     gdpBn: 59,     pubInvPctGdp: 0.07,  pubInvBn: 4.13    },
  { iso3: "TUV", name: "Tuvalu",                           gdpBn: 0.06,   pubInvPctGdp: 0.09,  pubInvBn: 0.005   },
  { iso3: "UGA", name: "Uganda",                           gdpBn: 50,     pubInvPctGdp: 0.05,  pubInvBn: 2.5     },
  { iso3: "UKR", name: "Ukraine",                          gdpBn: 178,    pubInvPctGdp: 0.045, pubInvBn: 8.01    },
  { iso3: "ARE", name: "United Arab Emirates",             gdpBn: 509,    pubInvPctGdp: 0.075, pubInvBn: 38.175  },
  { iso3: "GBR", name: "United Kingdom",                   gdpBn: 3126,   pubInvPctGdp: 0.028, pubInvBn: 87.528  },
  { iso3: "USA", name: "United States",                    gdpBn: 28800,  pubInvPctGdp: 0.035, pubInvBn: 1008.0  },
  { iso3: "URY", name: "Uruguay",                          gdpBn: 77,     pubInvPctGdp: 0.035, pubInvBn: 2.695   },
  { iso3: "UZB", name: "Uzbekistan",                       gdpBn: 100,    pubInvPctGdp: 0.065, pubInvBn: 6.5     },
  { iso3: "VUT", name: "Vanuatu",                          gdpBn: 1,      pubInvPctGdp: 0.07,  pubInvBn: 0.07    },
  { iso3: "VEN", name: "Venezuela",                        gdpBn: 95,     pubInvPctGdp: 0.03,  pubInvBn: 2.85    },
  { iso3: "VNM", name: "Vietnam",                          gdpBn: 430,    pubInvPctGdp: 0.065, pubInvBn: 27.95   },
  { iso3: "YEM", name: "Yemen",                            gdpBn: 18,     pubInvPctGdp: 0.03,  pubInvBn: 0.54    },
  { iso3: "ZMB", name: "Zambia",                           gdpBn: 29,     pubInvPctGdp: 0.05,  pubInvBn: 1.45    },
  { iso3: "ZWE", name: "Zimbabwe",                         gdpBn: 21,     pubInvPctGdp: 0.045, pubInvBn: 0.945   },
];

/** Quick lookup map: iso3 → CountryData */
export const COUNTRIES_BY_ISO3 = new Map<string, CountryData>(
  COUNTRIES_DATA.map((c) => [c.iso3, c])
);

/** Resolve a country name from an ISO3 code, falling back to the raw value */
export function resolveCountryName(iso3OrName: string): string {
  return COUNTRIES_BY_ISO3.get(iso3OrName)?.name ?? iso3OrName;
}
